### ISSUE TITLE
Is there any other version of the program?

### ISSUE THREAD

**Issue by songwaimai** [KamitaniLab/End2EndDeepImageReconstruction#3]
Thank you very much for sharing, I learned a lot!
Do you have the tensorflow version or the pytorch version of the program and the model?

**Comment by shen-gh** [comment]
Sorry, not yet.
We are planning to implement it using tensorflow or pytorch.

**Comment by songwaimai** [comment]
Thanks for your reply and looking forward to your tensorflow or pytorch version!
